name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    CARGO_TERM_COLOR: always

jobs:
    common:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: nightly
                override: true
            - name: rustup
              run: rustup component add rustfmt clippy --toolchain nightly-x86_64-unknown-linux-gnu
            - uses: actions/checkout@v3
            - uses: Swatinem/rust-cache@v2
            - name: Format
              run: cargo fmt -- --check
            - name: Test
              run: cargo test
            - name: Clippy
              run: cargo clippy --tests -- -D clippy::pedantic